### ISSUE TITLE
Plugin fails on systems w/o Edge

### ISSUE THREAD

**Issue by forbesjo** [litixsoft/karma-detect-browsers#17]
The latest update broke non-Windows users:
```
.../node_modules/karma-detect-browsers/index.js:24
                browserPaths = browser.DEFAULT_CMD[process.platform] || [],
                                                  ^

TypeError: Cannot read property 'darwin' of undefined
```

https://github.com/litixsoft/karma-detect-browsers/blob/master/browsers/Edge.js#L7

The early return is making the Edge browser object `undefined`

**Comment by nickmccurdy** [comment]
That's odd, this seems to work fine for me on macOS. I'm not sure why DEFAULT_CMD would be undefined, since it's defined in Edge.js. Please try clearing your `node_modules` and `npm install`ing again, and let me know if you still run into issues.

**Comment by nickmccurdy** [comment]
That's odd, this seems to work fine for me on macOS. While the error handling could be improved in my opinion, `resolve.sync()` still isn't expected to fail. Please try clearing your `node_modules` and `npm install`ing again, and let me know if you still run into issues.

**Comment by forbesjo** [comment]
Still fails for me.

**Comment by forbesjo** [comment]
Seems to be the same failure here https://travis-ci.org/litixsoft/karma-detect-browsers/jobs/173933385

**Comment by nickmccurdy** [comment]
It seems like the [karma-safaritechpreview-launcher](https://github.com/marcoscaceres/karma-safaritechpreview-launcher) dependency only supports Node 5+, due to usage of ES6/7/something syntax.

**Comment by nickmccurdy** [comment]
See https://github.com/marcoscaceres/karma-safaritechpreview-launcher/issues/3#issuecomment-258965310.

**Comment by gkatsev** [comment]
I'm not sure it's just karma-safaritechpreview-launcher that's the issue. We have a videojs build that runs on codeship and it fails: https://github.com/videojs/video.js/pull/3754 and we do not have the safari tech preview launcher installed: https://github.com/videojs/video.js/blob/master/package.json#L90-L101

**Comment by gkatsev** [comment]
If I change [this line](https://github.com/litixsoft/karma-detect-browsers/blob/760ad0398606d5504d587115e9c353306b6f621e/browsers/Edge.js#L7) locally to be `CMD = ''`, then everything works fine.

**Comment by nickmccurdy** [comment]
Hm, it seems like we've been discussing two unrelated issues that both started happening recently. There's the original CMD issue, and a regression in a dependency of karma-safaritechpreview-launcher.

@gkatsev Would it be possible for you to send me the log for your failing codeship build?

**Comment by gkatsev** [comment]
Here's a stack trace of when I run locally via `grunt karma --stack --verbose --debug`:
```sh
TypeError: Cannot read property 'darwin' of undefined
    at getInstalledBrowsers (/Users/gkatsevman/p/video.js/node_modules/karma-detect-browsers/index.js:25:51)
    at DetectBrowsers (/Users/gkatsevman/p/video.js/node_modules/karma-detect-browsers/index.js:65:28)
    at Array.invoke (/Users/gkatsevman/p/video.js/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at null.get (/Users/gkatsevman/p/video.js/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at /Users/gkatsevman/p/video.js/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at null.Server._start (/Users/gkatsevman/p/video.js/node_modules/karma/lib/server.js:142:21)
    at null.invoke (/Users/gkatsevman/p/video.js/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at null.Server.start (/Users/gkatsevman/p/video.js/node_modules/karma/lib/server.js:103:18)
    at Object.<anonymous> (/Users/gkatsevman/p/video.js/node_modules/grunt-karma/tasks/grunt-karma.js:136:14)
    at Object.<anonymous> (/Users/gkatsevman/p/video.js/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/gkatsevman/p/video.js/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/gkatsevman/p/video.js/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/gkatsevman/p/video.js/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/gkatsevman/p/video.js/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/gkatsevman/p/video.js/node_modules/grunt/lib/util/task.js:227:11
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by kumavis** [comment]
+1

**Comment by gkatsev** [comment]
Thanks @LitixThomas!
